control-center/include/etc/confluent/docker/run
We don't want to print the environment variables in the logs during startup because they contain sensitive data.
=> ST-3599: Remove show_env function because it exposes secrets

control-center/Dockerfile.ubi8
non base docker scripts that run yum update will cause issues because we rely on the base image's package versions, not the packages yup update fetches
=> ST-4240: remove yum update in non base Docker images

Jenkinsfile, control-center/pom.xml, pom.xml
Setting the jenkins config to use nano versioning. Removed all of the snapshot versions and replaced with nano versions. Updated all of the dependency versions.
These changes will be merged during phase two of the nano versioning roll out.
=> ST-3461: Implement nano versioning

.gitignore, control-center/include/etc/confluent/docker/control-center.properties.template
Jira: https://confluentinc.atlassian.net/browse/MMA-9263
What
Allow users to pass `config.providers*`properties required to encrypt password/secrets
=> [MMA-9263]: Allow "config.providers" properties to be specified

control-center/include/etc/confluent/docker/control-center.properties.template, control-center/test/test_control_center_props_validation.py
Jira ticket: https://confluentinc.atlassian.net/browse/MMA-10870
Summary: Refactored and updated c3 template file to correctly translate existing c3 properties, and added a series of properties validation test that validate translation from `env_props` to `c3_props` is correct.
- Created `SET_PROPERTIES` macro function to centralize property setting logic. 
- Removed unnecessary newlines and `None` in the resulting template file. 
- Removed the following properties since they're incorrect/unsupported properties: `CONTROL_CENTER_CPREST_URL`, `CONFIG_PROVIDERS`, `CONFIG_PROVIDERS_SECUREPASS_CLASS`.
- Modified/Refactored property precedence (look at the table below for more details).
| Properties | Not Changed  | Changed  |
| :---:   | :-: | :-: |
| Required props | They're still either set …
=> MMA-10870: refactor c3 template file and add props validation test

control-center/Dockerfile.ubi8
This restores the root groups write access to confluent service directories.
Internally (@rohit2b) and externally (@erikgb) this change works in an OpenShift context.
=> fix: Restore root group write access to directories

control-center/include/etc/confluent/docker/control-center.properties.template, control-center/test/test_control_center_props_validation.py
Jira ticket: https://confluentinc.atlassian.net/browse/MMA-11806
Stop hardcoding the translations of `confluent.metrics.*` and `confluent.monitoring.interceptor.*` properties introduced in https://confluentinc.atlassian.net/browse/MMA-10870. This is because the hardcoded list might not be exhaustive, resulting in incorrect translation raised by MMA-11806.
Note: [control-center.properties.template](https://github.com/confluentinc/control-center-images/pull/52/files#diff-e85fff2a7ca9f755d48c8cc3f0ad6900f2dfabbc966ecc367f9b4d756f2c424c) has a few custom functions:
- SET_PROPERTIES (added due to some c3 properties have irregular translations)
- SET_PROPERTIES_WITH_ENV_TO_PROPS (standard way of translating properties)
- SET_PROPERTIES_WITH_ENV_TO_PROPS_WITH_TWO_PREFIXES (added due to the …
=> MMA-11806: Stop hardhoding confluent.metrics.* and confluent.monitoring.interceptor.* properties

control-center/include/etc/confluent/docker/control-center.properties.template, control-center/test/test_control_center_props_validation.py
Pass following properties to control-center
*   'config.providers' via 'CONFIG_PROVIDERS'
*  'config.providers.securepass.class' via CONFIG_PROVIDERS_SECUREPASS_CLASS'
=> RCCA-8895: Update `control-center.properties.template` file

service.yml
This PR is part of Jenkins to Semaphore Migration. In this PR we enable semaphore to sign images. This is required as per the comment mentioned at https://confluentinc.atlassian.net/browse/MMA-14178?focusedCommentId=2577551
More details on the work can be found at: [MMA-14178](https://confluentinc.atlassian.net/browse/MMA-14178?focusedCommentId=2539706)
Instructions used for migration: [Migration Guide](https://confluentinc.atlassian.net/wiki/spaces/TOOLS/pages/3211693075/Jenkins+-+Semaphore+self+migration+guide#How-do-I-migrate-dockerfile%3F) & [More info on configs used](https://confluentinc.atlassian.net/browse/MMA-14178?focusedCommentId=2539706)
[MMA-14178]: https://confluentinc.atlassian.net/browse/MMA-14178?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHV …
=> [MMA-14178] Jenkins to Semaphore Migration - Sign Images

service.yml
This PR is part of Jenkins to Semaphore Migration. In this PR we enable semaphore to sign images. This is required as per the comment mentioned at https://confluentinc.atlassian.net/browse/MMA-14178?focusedCommentId=2577551
More details on the work can be found at: [MMA-14178](https://confluentinc.atlassian.net/browse/MMA-14178?focusedCommentId=2539706)
Instructions used for migration: [Migration Guide](https://confluentinc.atlassian.net/wiki/spaces/TOOLS/pages/3211693075/Jenkins+-+Semaphore+self+migration+guide#How-do-I-migrate-dockerfile%3F) & [More info on configs used](https://confluentinc.atlassian.net/browse/MMA-14178?focusedCommentId=2539706)
[MMA-14178]: https://confluentinc.atlassian.net/browse/MMA-14178?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHV …
=> [MMA-14178] Jenkins to Semaphore Migration - Sign Images 

control-center/pom.xml, pom.xml
=> Fix version bump in pom.xml

control-center/pom.xml, pom.xml
=> Fix version bump in pom.xml for 7.1.x

control-center/pom.xml, pom.xml
=> Fix version bump in pom.xml for 7.2.x

control-center/pom.xml, pom.xml
=> Fix version bump in pom.xml for 7.4.x

control-center/pom.xml, pom.xml
=> Fix version bump in pom.xml for 7.6.x

control-center/pom.xml, pom.xml
=> Fix version bump in pom.xml for 7.5.x

.github/CODEOWNERS, .semaphore/cp_dockerfile_build.yml, .semaphore/project.yml, .semaphore/semaphore.yml
1. During Jenkins to Semaphore migration service-bot added some changes to an exiting PR confluentinc/control-center-images/pull/67. 
2. Earlier this PR was merged as is but we later realised all changes from this PR were not required so this PR is reverted at confluentinc/control-center-images/pull/75 & only required changes are cherry-picked in this PR.
3. Meanwhile since the changes are reverted service bot raised a different PR with same changes at confluentinc/control-center-images/pull/77 so cherry-picked commits from this instead.
4. **How to verify?** Ensure all changes from .semaphore folder in the PR confluentinc/control-center-images/pull/77 are picked up
Will make sure that the changes are reviewed by c3 & cp-build team.
=> [MMA-14178] Back-Porting Jenkins Semaphore migration changes

service.yml
Currently latest control-center-images image is not pushed to repository. Adding `push_latest: true` to enable this as per the request at https://confluent.slack.com/archives/C06N5PM0W0G/p1716356782234999
=> [MMA-14178] MINOR: Push images to repository

service.yml
Service Bot updates are failing due to python version related issue so updating python version to latest.
`CMD: sem-version python 2.7`
`[2024-05-22T07:42:25+00:00]: specified version of Python is end of life. Must be >= 3.7. If you think you received this message in error and you are a Confluent employee, see https://go/semaphore-support. Otherwise, contact the maintainer of the Semaphore project.`
Corresponding Build: https://semaphore.ci.confluent.io/jobs/3eb4ccc8-9cf2-4c22-b3d7-6bfddf87c3e8
=> [MMA-14178] MINOR: Update python version

control-center/include/etc/confluent/docker/control-center.properties.template
this file was update unintentionally in one of service bot PR  https://github.com/confluentinc/control-center-images/pull/75
https://confluent.slack.com/archives/C01T51MQKEF/p1717580350066479
Some PR checks are failing, these checks are running on jenkins and some paths are not updated. Ignoring these checks. The main PR job is moved to semaphore which is passing.
] ===> Installing control-center...
11:11:34  [INFO] curl: (22) The requested URL returned error: 404 Not Found
11:11:34  [INFO] 
11:11:34  [INFO] error: https://s3-us-west-2.amazonaws.com/dev-confluent-packages-654654529379-us-west-2/7.0.x/null/rpm/7.0/archive.key: import read failed(2).
=> [MMA-115579] - reverting the control center template file to original state

service.yml
Deploy step is failing in CI with the error
`[ERROR] Failed to execute goal org.apache.maven.plugins:maven-deploy-plugin:2.8.2:deploy (default-deploy) on project control-center-images-parent: Failed to deploy artifacts: Could not transfer artifact io.confluent.control-center-images:control-center-images-parent:pom:7.2.12-7 from/to confluent-codeartifact-internal (https://confluent-519856050701.d.codeartifact.us-west-2.amazonaws.com/maven/maven-snapshots/): status code: 403, reason phrase: Forbidden (403) -> [Help 1]00:34`
As per the suggestion from devprod team [here](https://confluent.slack.com/archives/C01RVE8R162/p1723532973293369?thread_ts=1721020933.826369&cid=C01RVE8R162) making the changes
Previous build failure: https://semaphore.ci.confluent.io/jobs/b5eec7b7-e1d8-4235-8af7-fdbcf12 …
=> Fix forbidden issue in deploy step in CI

service.yml
Deploy step is failing in CI with the error
`[ERROR] Failed to execute goal org.apache.maven.plugins:maven-deploy-plugin:2.8.2:deploy (default-deploy) on project control-center-images-parent: Failed to deploy artifacts: Could not transfer artifact io.confluent.control-center-images:control-center-images-parent:pom:7.1.14-12 from/to confluent-codeartifact-internal (https://confluent-519856050701.d.codeartifact.us-west-2.amazonaws.com/maven/maven-snapshots/): status code: 403, reason phrase: Forbidden (403) -> [Help 1]`
As per the suggestion from devprod & build team [here](https://confluent.slack.com/archives/C01RVE8R162/p1723544491939869?thread_ts=1721020933.826369&cid=C01RVE8R162) making the changes
Previous build failure: https://semaphore.ci.confluent.io/jobs/1c989b0b-5de3-45fc-883a-9b8 …
=> Fix forbidden issue in deploy step in CI for enterprise 

.semaphore/cp_dockerfile_build.yml
Build for control-center-images is failing with the issue
> [ERROR] Failed to execute goal org.owasp:dependency-check-maven:7.4.4:check (default) on project control-center-images-parent: Fatal exception(s) analyzing Control Center Docker Images: One or more exceptions occurred during analysis:00:49
[ERROR] 	UpdateException: Unable to download meta file: https://s3-us-west-2.amazonaws.com/confluent-packaging-tools/nvd.nist.gov/nvdcve-1.1-modified.meta00:49
[ERROR] 		caused by DownloadFailedException: Download failed, unable to retrieve 'https://s3-us-west-2.amazonaws.com/confluent-packaging-tools/nvd.nist.gov/nvdcve-1.1-modified.meta'; Error downloading file https://s3-us-west-2.amazonaws.com/confluent-packaging-tools/nvd.nist.gov/nvdcve-1.1-modified.meta; unable to connect.00:49
[ERROR] …
=> Disable dependency check Temporarily 

.semaphore/cp_dockerfile_build.yml, .semaphore/semaphore.yml
The docker build is timing out for April release of FedRAMP due to 1 hr execution limit.
https://semaphore.ci.confluent.io/workflows/78263e99-7b9f-40d9-ab91-84549a78ce5f
=> Increase docker build time limit RC branch

.semaphore/cp_dockerfile_build.yml, .semaphore/semaphore.yml
The docker build is timing out for May release of FedRAMP due to 1 hr execution limit.
https://semaphore.ci.confluent.io/jobs/e8f48e86-d9a6-4ffd-a8fa-5e3bc1a59287
=> Increase docker build time limit FedRAMP branch
